name: rise-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - sympy
  - pandas
  - bokeh
  - rise
  - jupyter_nbextensions_configurator
  - tk
  - pip

